View/Controllers/CategoriaController.cs
using Model;
using Repository.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace View.Controllers
{
    public class CategoriaController : Controller
    {
        CategoriaRepository repository;

        public CategoriaController()
        {
            repository = new CategoriaRepository();
        }

        // GET: Categoria
        public ActionResult Index()
        {
            ViewBag.Categorias = repository.ObterTodos("");
            return View();
        }

        public ActionResult Cadastrar()
        {
            return View();
        }

        public ActionResult Store(string nome)
        {
            repository.Inserir(new Categoria() { Nome = nome });
            return RedirectToAction("Index");
        }

        public ActionResult Apagar(int id)
        {
            repository.Apagar(id);
            return RedirectToAction("Index");
        }

        public ActionResult Editar(int id)
        {
            ViewBag.Categoria = repository.ObterPeloId(id);
            return View();
        }

        public ActionResult Update(int id, string nome)
        {
            repository.Atualizar(new Categoria() { Id = id, Nome = nome });
            return RedirectToAction("Index");
        }
    }
}

View/Controllers/ClienteController.cs
using Model;
using Repository.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace View.Controllers
{
    public class ClienteController : Controller
    {
        ClienteRepository repository;

        public ClienteController()
        {
            repository = new ClienteRepository();
        }

        // GET: Cliente
        public ActionResult Index()
        {
            ViewBag.Clientes = repository.ObterTodos("");
            return View();
        }

        public ActionResult Cadastrar()
        {
            ContabilidadeRepository contabilidadeRepository = new ContabilidadeRepository();
            ViewBag.Contabilidades = contabilidadeRepository.ObterTodos("");
            return View();
        }

        public ActionResult Store(string nome,string cpf, int idContabilidade)
        {
            repository.Inserir(new Cliente() { Nome = nome, CPF = cpf, IdContabilidade = idContabilidade });
            return RedirectToAction("Index");
        }

        public ActionResult Apagar(int id)
        {
            repository.Apagar(id);
            return RedirectToAction("Index");
        }

        public ActionResult Editar(int id)
        {
            ContabilidadeRepository contabilidadeRepository = new ContabilidadeRepository();
            ViewBag.Contabilidades = contabilidadeRepository.ObterTodos("");
            ViewBag.Cliente = repository.ObterPeloId(id);
            return View();
        }

        public ActionResult Update(int id, string nome, string cpf, int idContabilidade)
        {
            repository.Atualizar(new Cliente() { Nome = nome, CPF = cpf, IdContabilidade = idContabilidade, Id = id });
            return RedirectToAction("Index");
        }
    }
}

View/Controllers/CompraController.cs
using Model;
using Repository.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace View.Controllers
{
    public class CompraController : Controller
    {

        // GET: Compra

        CompraRepository repository;

        public CompraController()
        {
            repository = new CompraRepository();
        }

        public ActionResult Index()
        {
            ViewBag.Compras = repository.ObterTodos("");
            return View();
        }
        public ActionResult Cadastrar()
        {
            CartaoCreditoRepository cartaoCreditoRepository = new CartaoCreditoRepository();
            ViewBag.Cartoes = cartaoCreditoRepository.ObterTodos("");
            return View();
        }

        public ActionResult Store(int idCartaoCredito, string valor, string datacompra)
        {
            repository.Inserir(new Compra()
            {
                IdCartaoCredito = idCartaoCredito,
                Valor = Convert.ToDecimal(valor.ToString().Replace(".", ",")),
                DataCompra = Convert.ToDateTime(datacompra)
            });
            return RedirectToAction("Index");
        }

        public ActionResult Apagar(int id)
        {
            repository.Apagar(id);
            return RedirectToAction("Index");
        }

        public ActionResult Editar(int id)
        {
            CartaoCreditoRepository cartaoCreditoRepository  = new CartaoCreditoRepository();
            ViewBag.Cartoes = cartaoCreditoRepository.ObterTodos("");

            ViewBag.Compra = repository.ObterPeloId(id);
            
            return View();
        }

        public ActionResult Update(int id, int idCartaoCredito, string valor, string datacompra)
        {
            Compra contaReceber = new Compra()
            {
                Id = id,
                IdCartaoCredito = idCartaoCredito,
                Valor = Convert.ToDecimal(valor.ToString()),
                DataCompra = Convert.ToDateTime(datacompra)
            };

            repository.Atualizar(contaReceber);
            return RedirectToAction("Index");
        }
    }
}

View/Controllers/UsuarioController.cs
using Model;
using Repository.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace View.Controllers
{
    public class UsuarioController : Controller
    {

        UsuarioRepository repository;


        public UsuarioController()
        {
            repository = new UsuarioRepository();
        }

        // GET: Usuario
        public ActionResult Index()
        {
            ViewBag.Usuarios = repository.ObterTodos("");
            return View();
        }

        public ActionResult Cadastrar()
        {
            ContabilidadeRepository contabilidadeRepository = new ContabilidadeRepository();
            ViewBag.Contabilidades = contabilidadeRepository.ObterTodos("");

            return View();
        }

        public ActionResult Store(string login, string senha, DateTime dataNascimento, int idContabilidade)
        {
            Usuario usuario = new Usuario();
            usuario.Login = login;
            usuario.Senha = senha;
            usuario.DataNascimento = dataNascimento;
            usuario.IdContabilidade = idContabilidade;

            repository.Inserir(usuario);
            return RedirectToAction("Index");
        }

        public ActionResult Apagar(int id)
        {
            repository.Apagar(id);
            return RedirectToAction("Index");
        }

        public ActionResult Editar(int id)
        {
            ContabilidadeRepository contabilidadeRepository = new ContabilidadeRepository();
            ViewBag.Contabilidades = contabilidadeRepository.ObterTodos("");

            ViewBag.Usuario = repository.ObterPeloId(id);
            return View();
        }

        public ActionResult Update(int id, string login, string senha, DateTime dataNascimento, int idContabilidade)
        {
            Usuario usuario = new Usuario();
            usuario.Id = id;
            usuario.Login = login;
            usuario.Senha = senha;
            usuario.DataNascimento = dataNascimento;
            usuario.IdContabilidade = idContabilidade;

            repository.Atualizar(usuario);
            return RedirectToAction("Index");
        }
    }
}

View/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/fontawesome-all.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <script src="~/Scripts/fontawesome/fontawesome.min.js"></script>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.js"></script>
</head>
<body style="padding:0">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
        <a class="navbar-brand" href="#">Contabilidade</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link"
                       href="@Url.Action("Index", "Categoria")">Categorias</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link"
                       href="@Url.Action("Index", "Contabilidade")">Contabilidades</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link"
                       href="@Url.Action("Index", "Cliente")">Clientes</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link"
                       href="@Url.Action("Index", "Usuario")">Usuários</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link"
                       href="@Url.Action("Index", "ContaPagar")">Contas a Pagar</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link"
                       href="@Url.Action("Index", "ContaReceber")">Contas a Receber</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link"
                       href="@Url.Action("Index", "CartaoCredito")">Cartões De Credito</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link"
                       href="@Url.Action("Index", "Compra")">Compras</a>
                </li>
            </ul>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
    </div>
</body>
</html>